version: '2'
services:
  zookeeper:
    build:
      context: zookeeper
      dockerfile: Dockerfile
    ports:
      - "2181:2181"
    expose:
      - 2181

  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.132.116
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-manager:
    image: kafkamanager/kafka-manager
    environment:
      ZK_HOSTS: zookeeper:2181
    ports:
      - "9000:9000"
